import { useEffect, useState } from 'react';
import { Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { useAuth } from './hooks/useAuth';
import { createLead, getLeads, getStats, removeLead, updateLead } from './services/leadService';

const emptyLead = { name: '', email: '', phone: '', company: '', source: 'website', status: 'new', notes: '', followUpDate: '' };
const statuses = ['new', 'contacted', 'qualified', 'converted', 'lost'];
const sources = ['website', 'linkedin', 'referral', 'instagram', 'google', 'other'];
const pretty = (value) => value ? value[0].toUpperCase() + value.slice(1) : '—';
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : '—';

function Protected({ children }) { const { auth, loading } = useAuth(); if (loading) return <div className="loading-screen">Loading your workspace…</div>; return auth ? children : <Navigate to="/login" replace />; }
function Login() { const { auth, login } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); if (auth) return <Navigate to="/dashboard" replace />;
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { await login(form.email, form.password); navigate('/dashboard'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="login-page"><form className="login-card" onSubmit={submit}><span className="brand-mark">P</span><h1>Welcome back</h1><p>Sign in to manage your lead pipeline.</p>{error && <div className="alert error">{error}</div>}<label>Email<input type="email" required autoComplete="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><button disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form></main>; }
function Shell({ children }) { const { auth, logout } = useAuth(); return <div className="app-shell"><aside><div className="logo"><span>P</span> Pipeline</div><nav><NavLink to="/dashboard">Dashboard</NavLink><NavLink to="/leads">Leads</NavLink></nav><div className="account"><b>{auth.user.name}</b><small>{auth.user.email}</small><button className="text-button" onClick={logout}>Sign out</button></div></aside><main className="content">{children}</main></div>; }
function Dashboard() { const { auth } = useAuth(); const [stats, setStats] = useState(null); const [leads, setLeads] = useState([]); const [error, setError] = useState(''); useEffect(() => { Promise.all([getStats(auth.token), getLeads(auth.token)]).then(([s, l]) => { setStats(s); setLeads(l.slice(0, 5)); }).catch((e) => setError(e.message)); }, [auth.token]); if (error) return <Shell><div className="alert error">{error}</div></Shell>; const items = [['Total leads', stats?.total, 'total'], ['New', stats?.new, 'new'], ['Contacted', stats?.contacted, 'contacted'], ['Converted', stats?.converted, 'converted']]; return <Shell><header><div><p className="eyebrow">OVERVIEW</p><h1>Your sales pipeline</h1><p>See what needs your attention today.</p></div><NavLink className="button-link" to="/leads">Manage leads</NavLink></header><section className="stats">{items.map(([label, value, key]) => <article className="stat" key={key}><span>{label}</span><strong>{stats ? value : '—'}</strong><i className={key} /></article>)}</section><section className="panel"><div className="panel-title"><h2>Recent leads</h2><NavLink to="/leads">View all</NavLink></div>{leads.length ? <LeadTable leads={leads} compact /> : <p className="empty">No leads yet. Add your first lead from the Leads page.</p>}</section></Shell>; }
function LeadTable({ leads, onEdit, onDelete, compact = false }) { return <div className="table-wrap"><table><thead><tr><th>Lead</th><th>Source</th><th>Status</th><th>Follow-up</th>{!compact && <th>Actions</th>}</tr></thead><tbody>{leads.map((lead) => <tr key={lead._id}><td><b>{lead.name}</b><small>{lead.email}{lead.company ? ` · ${lead.company}` : ''}</small></td><td>{pretty(lead.source)}</td><td><span className={`badge ${lead.status}`}>{pretty(lead.status)}</span></td><td>{formatDate(lead.followUpDate)}</td>{!compact && <td className="actions"><button className="icon-button" aria-label={`Edit ${lead.name}`} onClick={() => onEdit(lead)}>Edit</button><button className="danger-link" aria-label={`Delete ${lead.name}`} onClick={() => onDelete(lead)}>Delete</button></td>}</tr>)}</tbody></table></div>; }
function LeadModal({ lead, onClose, onSave }) { const [form, setForm] = useState(lead || emptyLead); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const change = (key, value) => setForm({ ...form, [key]: value }); async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { await onSave({ ...form, followUpDate: form.followUpDate || null }); onClose(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
 return <div className="modal-backdrop" role="presentation"><form className="modal" onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="lead-form-title"><div className="modal-head"><h2 id="lead-form-title">{lead ? 'Edit lead' : 'Add lead'}</h2><button type="button" className="text-button" onClick={onClose}>Close</button></div>{error && <div className="alert error">{error}</div>}<div className="form-grid"><label>Name<input required value={form.name} onChange={(e) => change('name', e.target.value)} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => change('email', e.target.value)} /></label><label>Phone<input value={form.phone} onChange={(e) => change('phone', e.target.value)} /></label><label>Company<input value={form.company} onChange={(e) => change('company', e.target.value)} /></label><label>Source<select value={form.source} onChange={(e) => change('source', e.target.value)}>{sources.map((x) => <option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={(e) => change('status', e.target.value)}>{statuses.map((x) => <option key={x}>{x}</option>)}</select></label><label>Follow-up date<input type="date" value={form.followUpDate ? form.followUpDate.slice(0, 10) : ''} onChange={(e) => change('followUpDate', e.target.value)} /></label><label className="full">Notes<textarea rows="4" value={form.notes} onChange={(e) => change('notes', e.target.value)} placeholder="Add a useful follow-up note…" /></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={busy}>{busy ? 'Saving…' : lead ? 'Save changes' : 'Create lead'}</button></div></form></div>; }
function Leads() { const { auth } = useAuth(); const [leads, setLeads] = useState([]); const [filters, setFilters] = useState({ search: '', status: '', source: '' }); const [modal, setModal] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const load = async () => { setLoading(true); try { const qs = new URLSearchParams(Object.entries(filters).filter(([, v]) => v)); setLeads(await getLeads(auth.token, qs.toString() ? `?${qs}` : '')); setError(''); } catch (e) { setError(e.message); } finally { setLoading(false); } }; useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id); }, [filters, auth.token]); const save = async (form) => { if (modal && modal !== 'new') await updateLead(auth.token, modal._id, form); else await createLead(auth.token, form); setMessage(modal === 'new' ? 'Lead created.' : 'Lead updated.'); await load(); }; const del = async (lead) => { if (!window.confirm(`Delete ${lead.name}? This cannot be undone.`)) return; try { await removeLead(auth.token, lead._id); setMessage('Lead deleted.'); load(); } catch (e) { setError(e.message); } };
 return <Shell><header><div><p className="eyebrow">LEAD MANAGEMENT</p><h1>Leads</h1><p>Track every conversation from first contact to conversion.</p></div><button onClick={() => setModal('new')}>+ Add lead</button></header>{message && <div className="alert success">{message}</div>}{error && <div className="alert error">{error}</div>}<section className="panel"><div className="filters"><input aria-label="Search leads" placeholder="Search name, email, company…" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select aria-label="Filter by status" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{statuses.map((x) => <option key={x} value={x}>{pretty(x)}</option>)}</select><select aria-label="Filter by source" value={filters.source} onChange={(e) => setFilters({ ...filters, source: e.target.value })}><option value="">All sources</option>{sources.map((x) => <option key={x} value={x}>{pretty(x)}</option>)}</select></div>{loading ? <p className="empty">Loading leads…</p> : leads.length ? <LeadTable leads={leads} onEdit={setModal} onDelete={del} /> : <p className="empty">No leads match these filters.</p>}</section>{modal && <LeadModal lead={modal === 'new' ? null : modal} onClose={() => setModal(null)} onSave={save} />}</Shell>; }
function NotFound() { return <Navigate to="/dashboard" replace />; }
export default function App() { return <Routes><Route path="/login" element={<Login />} /><Route path="/dashboard" element={<Protected><Dashboard /></Protected>} /><Route path="/leads" element={<Protected><Leads /></Protected>} /><Route path="*" element={<NotFound />} /></Routes>; }
